### ISSUE TITLE
error occurred when downloading HTML

### ISSUE THREAD

**Issue by davirond** [yageek/iSpoiler#4]
Hi 

got a permanent "error occurred when downloading HTML" message whenever there is an image to download from a cache page.
![capture d ecran 2015-06-10 a 20 59 07](https://cloud.githubusercontent.com/assets/12834770/8091335/8e8300e4-0fb3-11e5-88a8-2687134d7e1f.png)
 I can't attach a sample GPX file but can send it over email.

Thanks

**Comment by yageek** [comment]
The provided GPX is invalid
