### ISSUE TITLE
iSpoiler OS X Bug

### ISSUE THREAD

**Issue by Stefan1982** [yageek/iSpoiler#5]
hello under OS X 10.11.1 (El Capitan) crashed ispoiler 1.2.4. if you choose a GPX file. I ask for an update.

**Comment by yageek** [comment]
Could you provide the GPX you used and some infos about the computer you have ?

**Comment by Stefan1982** [comment]
hello i have normal gpx file from geocaching.com, i have a MacBook Pro (Retina, 15', mid 2014),

**Comment by Stefan1982** [comment]
Will there soon be an update?

**Comment by yageek** [comment]
I checked withe some random file and I had no problem. Could you provide me the GPX file you used ? You can send it to me by email or drag and drop the file here ? May be a Dropbox Link ?
